// ==========================================================================
// 📖 课文与字词矩阵数据（全篇词/短语无死角拼音与双语翻译） - data.js
// ==========================================================================

const lessonTitle = "深刻的故事";

const lessonData = [
    // --- 第1段 ---
    ["有这样一个", "yǒu zhè yàng yí gè", "there is such a", "ada sebuah"],
    ["真实的故事，", "zhēn shí de gù shi", "true story", "kisah benar"],
    ["令人深思。", "lìng rén shēn sī", "thought-provoking / food for thought", "membuatkan orang berfikir dalam / merenung"],
    ["\n", "", "", ""],

    // --- 第2段 ---
    ["圣诞节", "shèng dàn jié", "Christmas", "Hari Krismas"],
    ["临近，", "lín jìn", "approaching / drawing near", "semakin hampir / menjelang"],
    ["美国芝加哥", "měi guó zhī jiā gē", "Chicago, USA", "Chicago, Amerika Syarikat"],
    ["西北郊的", "xī běi jiāo de", "northwestern suburb of", "pinggir bandar barat laut"],
    ["帕克里奇镇", "pà kè lǐ qí zhèn", "Park Ridge Town", "Pekan Park Ridge"],
    ["到处", "dào chù", "everywhere", "di mana-mana sahaja / rata-rata"],
    ["洋溢着", "yáng yì zhe", "brimming with / permeated with", "dilimpahi dengan / diselubungi"],
    ["喜庆、", "xǐ qìng", "festive / joyous", "meriah / suasana gembira"],
    ["热烈的", "rè liè de", "warm / enthusiastic", "hangat / rancak"],
    ["节日气氛。", "jié rì qì fēn", "festive atmosphere", "suasana perayaan"],
    ["\n", "", "", ""],

    // --- 第3段 ---
    ["正在读中学的", "zhèng zài dú zhōng xué de", "currently studying in high school", "yang sedang belajar di sekolah menengah"],
    ["谢丽", "xiè lì", "Xieli (name)", "Xieli"],
    ["拿着一叠", "ná zhe yì dié", "holding a stack of", "memegang seikat / setumpuk"],
    ["不久前", "bù jiǔ qián", "not long ago", "tidak lama dahulu"],
    ["收到的", "shōu dào de", "received", "yang diterima"],
    ["圣诞贺卡，", "shèng dàn hè kǎ", "Christmas cards", "kad ucapan Krismas"],
    ["打算在", "dǎ suàn zài", "planning to in front of", "berniat di hadapan"],
    ["好朋友", "hǎo péng you", "good friend", "sahabat karib"],
    ["希拉里", "xī lā lǐ", "Hillary (name)", "Hillary"],
    ["面前", "miàn qián", "in front of", "hadapan"],
    ["炫耀一番。", "xuàn yào yī fān", "show off / flaunt", "menunjuk-nunjuk / memegah diri"],
    ["谁知", "shéi zhī", "who would have thought / unexpectedly", "siapa sangka / tidak diduga"],
    ["希拉里", "xī lā lǐ", "Hillary", "Hillary"],
    ["却", "què", "however / but", "namun / tetapi"],
    ["拿出了", "ná chū le", "took out", "mengeluarkan"],
    ["比她", "bǐ tā", "than her", "berbanding dia"],
    ["多十倍的", "duō shí bèi de", "ten times more", "sepuluh kali ganda lebih banyak"],
    ["圣诞贺卡,", "shèng dàn hè kǎ", "Christmas cards", "kad ucapan Krismas"],
    ["这令她", "zhè lìng tā", "this made her", "ini membuatkannya"],
    ["羡慕不已。", "xiàn mù bù yǐ", "envious / admire immensely", "amat kagum / cemburu sekali"],
    ["\n", "", "", ""],

    // --- 第4段 ---
    ["“你怎么", "nǐ zěn me", "how do you", "bagaimana kamu"],
    ["有这么多", "yǒu zhè me duō", "have so many", "mempunyai begitu banyak"],
    ["的朋友？", "de péng you", "friends", "sahabat / kawan"],
    ["这中间", "zhè zhōng jiān", "in this / between this", "di sebalik ini"],
    ["有什么", "yǒu shén me", "is there any", "apakah ada"],
    ["诀窍吗？”", "jué qiào ma", "secret of success / knack / trick", "诀窍 / rahsia kejayaan / petua?"],
    ["谢丽", "xiè lì", "Xieli", "Xieli"],
    ["惊奇地问。", "jīng qí dì wèn", "asked in surprise", "bertanya dengan hairan / pelik"],
    ["\n", "", "", ""],

    // --- 第5段 ---
    ["“诀窍吗……", "jué qiào ma", "Secret? ...", "Rahsia kejayaan? ..."],
    ["就是要", "jiù shì yào", "is just to", "adalah semestinya"],
    ["学会", "xué huì", "learn to", "belajar untuk"],
    ["真诚、", "zhēn chéng", "sincerely", "ikhlas / tulus"],
    ["热情地", "rè qíng dì", "warmly / enthusiastically", "dengan mesra / penuh semangat"],
    ["欣赏别人。”", "xīn shǎng bié rén", "appreciate others / admire others", "menghargai / mengagumi orang lain."],
    ["希拉里", "xī lā lǐ", "Hillary", "Hillary"],
    ["给谢丽", "gěi xiè lì", "to Xieli", "kepada Xieli"],
    ["讲了", "jiǎng le", "told", "menceritakan"],
    ["两年前", "liǎng nián qián", "two years ago", "dua tahun yang lalu"],
    ["她的一段", "tā de yí duàn", "a period of her", "sebahagian daripada... nya"],
    ["经历……", "jīng lì", "experience", "pengalaman..."],
    ["\n", "", "", ""],

    // --- 第6段 ---
    ["“那是个", "nà shì gè", "That was a", "Ia merupakan sebuah"],
    ["春天，", "chūn tiān", "spring", "musim bunga"],
    ["一个", "yí gè", "a", "seorang / sebuah"],
    ["暖洋洋的", "nuǎn yáng yáng de", "pleasantly warm", "yang suam-suam kuku / selesa panas"],
    ["中午，", "zhōng wǔ", "noon", "tengah hari"],
    ["我和爸爸", "wǒ hé bà ba", "my dad and I", "saya dan ayah"],
    ["在郊区公园", "zài jiāo qū gōng yuán", "in the suburban park", "di taman pinggir bandar"],
    ["散步。", "sàn bù", "take a walk / stroll", "bersiar-siar / berjalan-jalan"],
    ["在那儿，", "zài nà r", "over there", "di sana"],
    ["我看见", "wǒ kàn jiàn", "I saw", "saya melihat"],
    ["一个很", "yí gè hěn", "a very", "seorang yang sangat"],
    ["滑稽的", "huá jī de", "funny / comical / ludicrous", "lucu / melucukan"],
    ["老太太。", "lǎo tài tai", "old lady", "wanita tua / nenek"],
    ["天气", "tiān qì", "the weather", "cuaca"],
    ["那么暖和，", "nà me nuǎn huo", "so warm", "begitu suam / selesa"],
    ["她却", "tā què", "she however", "dia bagaimanapun"],
    ["紧裹着", "jǐn guǒ zhe", "tightly wrapped in", "membungkus rapat / memakai ketat"],
    ["一件厚厚的", "yí jiàn hòu hòu de", "a thick", "sehelai... yang tebal"],
    ["羊绒大衣，", "yáng róng dà yī", "cashmere coat", "baju sejuk bulu kambing / kot kasmir"],
    ["脖子上", "bó zi shàng", "on the neck", "di atas leher"],
    ["围着", "wéi zhe", "surrounded / wearing around", "memakai / melilit"],
    ["一条", "yì tiáo", "a (classifier for scarves/rivers)", "sehelai"],
    ["毛皮围巾，", "máo pí wéi jīn", "fur scarf", "skarf bulu binatang"],
    ["仿佛", "fǎng fú", "as if / as though", "seolah-olah / seakan-akan"],
    ["天上", "tiān shàng", "in the sky", "di langit"],
    ["正下着", "zhèng xià zhe", "is falling / snowing right now", "sedang turun"],
    ["鹅毛大雪。", "é máo dà xuě", "heavy snowfall like goose feathers", "salji yang amat tebal"],
    ["我轻轻地", "wǒ qīng qīng dì", "I gently", "saya dengan perlahan-lahan"],
    ["拽了一下", "zhuài le yí xià", "tugged / pulled slightly", "menarik sedikit"],
    ["爸爸的", "bà ba de", "dad's", "ayah punya"],
    ["胳膊", "gē bo", "arm", "lengan"],
    ["说：", "shuō", "saying", "berkata"],
    ["‘爸爸，", "bài ba", "Dad,", "Ayah,"],
    ["你看", "nǐ kàn", "look at", "lihatlah"],
    ["那位", "nà wèi", "that (person)", "warga tua... itu"],
    ["老太太的", "lǎo tài tai de", "old lady's", "wanita tua punya"],
    ["样子", "yàng zi", "appearance / look", "rupa / keadaan"],
    ["多可笑啊。’", "duō kě xiào a", "how laughable / funny!", "betapa lucunya / menggelikan hati!"],
    ["\n", "", "", ""],

    // --- 第7段 ---
    ["当时", "dāng shí", "at that time", "pada ketika itu"],
    ["爸爸的", "bà ba de", "dad's", "ayah punya"],
    ["表情", "biǎo qíng", "expression / countenance", "ekspresi muka / riak wajah"],
    ["显得", "xiǎn de", "looked / appeared", "kelihatan / nampak"],
    ["特别的", "tè bié de", "especially / unusually", "amat / sangat / luar biasa"],
    ["严肃。", "yán sù", "serious / solemn", "serius / tegas"],
    ["他沉默了", "tā chén mò le", "he fell silent", "dia mendiamkan diri"],
    ["一会儿", "yí huì r", "a moment", "sebentar / sekejap"],
    ["说：", "shuō", "said", "berkata"],
    ["‘希拉里，", "xī lā lǐ", "Hillary,", "Hillary,"],
    ["我突然", "wǒ tū rán", "I suddenly", "saya tiba-tiba"],
    ["发现", "fā xiàn", "discovered / realized", "mendapati / sedar"],
    ["你缺少", "nǐ quē shǎo", "you lack", "kamu kekurangan"],
    ["一种本领，", "yì zhǒng běn lǐng", "a kind of ability / skill", "sejenis kebolehan / kemahiran"],
    ["你不会", "nǐ bú huì", "you don't know how to", "kamu tidak tahu / pandai"],
    ["欣赏别人。", "xīn shǎng bié rén", "appreciate others", "menghargai / mengagumi orang lain."],
    ["这证明", "zhè zhèng míng", "this proves", "ini membuktikan bahawa"],
    ["你在与别人的", "nǐ zài yǔ bié rén de", "you in with others'", "kamu dalam pergaulan dengan orang lain punya"],
    ["交往中", "jiāo wǎng zhōng", "interaction / socializing", "pergaulan / hubungan"],
    ["少了一份", "shǎo le yí fèn", "lacked a piece of", "kekurangan sebahagian"],
    ["真诚", "zhēn chéng", "sincerity", "keikhlasan / ketulusan"],
    ["和", "hé", "and", "dan"],
    ["友善。’", "yǒu shàn", "friendliness / kindness", "sifat baik hati / ramah."],
    ["\n", "", "", ""],

    // --- 第8段 ---
    ["当时", "dāng shí", "at that time", "pada ketika itu"],
    ["我觉得", "wǒ jué de", "I felt", "saya berasa"],
    ["爸爸", "bà ba", "dad", "ayah"],
    ["有些", "yǒu xiē", "somewhat / a bit", "agak / sedikit"],
    ["小题大作了，", "xiáo tí dà zuò le", "make a mountain out of a molehill", "memperbesar-besarkan perkara kecil"],
    ["就很不服气地", "jiù hěn bù fú qì dì", "then very unconvincedly / defiantly", "lalu dengan tidak puas hati / membantah"],
    ["问", "wèn", "asked", "bertanya"],
    ["爸爸：", "bà ba", "dad", "ayah:"],
    ["‘你难道", "nǐ nán dào", "do you mean to say (rhetorical)", "adakah kamu sememangnya / takkan"],
    ["不觉得", "bù jué de", "don't think", "tidak berasa"],
    ["那位", "nà wèi", "that", "warga tua... itu"],
    ["老太太的", "lǎo tài tai de", "old lady's", "wanita tua punya"],
    ["样子", "yàng zi", "appearance", "rupa / keadaan"],
    ["很可笑吗？’", "hěn kě xiào ma", "is very funny?", "sangat lucu?"],
    ["\n", "", "", ""],

    // --- 第9段 ---
    ["爸爸", "bà ba", "dad", "ayah"],
    ["说：", "shuō", "said", "berkata"],
    ["‘和你相反，", "hé nǐ xiāng fǎn", "contrary to you", "berbalikan dengan kamu"],
    ["我很", "wǒ hěn", "I very much", "saya sangat"],
    ["欣赏", "xīn shǎng", "appreciate / admire", "menghargai / mengagumi"],
    ["那位", "nà wèi", "that", "wanita tua... itu"],
    ["老太太。’", "lǎo tài tai", "old lady", "wanita tua."],
    ["我听了", "wǒ tīng le", "I heard it", "saya mendengarnya"],
    ["感到", "gǎn dào", "felt / experienced", "berasa"],
    ["诧异。", "chà yì", "astonished / surprised", "hairan / tercengang."],
    ["\n", "", "", ""],

    // --- 第10段 ---
    ["爸爸", "bà ba", "dad", "ayah"],
    ["接着说：", "jiē zhe shuō", "continued to say", "menyambung kata:"],
    ["‘那位", "nà wèi", "that", "warga tua... itu"],
    ["老太太", "lǎo tài tai", "old lady", "wanita tua"],
    ["穿着大衣，", "chuān zhe dà yī", "wearing a coat", "memakai kot / baju sejuk"],
    ["围着围巾，", "wéi zhe wéi jìn", "wearing a scarf", "melilit skarf"],
    ["也许是", "yě xǔ shì", "perhaps it is", "mungkin sememangnya"],
    ["生病初愈，", "shēng bìng chū yù", "just recovered from an illness", "baru sembuh daripada sakit"],
    ["身体", "shēn tǐ", "body / health", "tubuh badan"],
    ["还不太", "hái bú tài", "still not very", "masih tidak berapa"],
    ["舒服。", "shū fu", "comfortable / well", "selesa / sihat."],
    ["但你看", "dàn nǐ kàn", "but you look at", "tetapi kamu lihatlah"],
    ["她的表情，", "tā de biǎo qíng", "her expression", "riak wajahnya"],
    ["她注视着", "tā zhù shì zhe", "she is gazing at", "dia sedang menatap"],
    ["树枝上", "shù zhī shàng", "on the tree branch", "di atas dahan pokok"],
    ["一朵", "yì duǒ", "a (classifier for flowers)", "sekuntum"],
    ["清香、", "qīng xiāng", "fragrant / sweet-scented", "yang harum / wangi"],
    ["漂亮的", "piào liang de", "beautiful", "indah / cantik punya"],
    ["丁香花，", "dīng xiāng huā", "lilac flower", "bunga lilak / cengkih"],
    ["表情是", "biǎo qíng shì", "expression is", "riak wajahnya adalah"],
    ["那么地", "nà me de", "so / in that way", "sedemikian begitu"],
    ["生动，", "shēng dòng", "vivid / lively", "hidup / penuh penghayatan"],
    ["你不认为", "nǐ bù rèn wéi", "don't you think", "bukankah kamu menganggap"],
    ["很可爱吗？", "hěn kě ài ma", "is very lovely?", "amat comel / menarik?"],
    ["她", "tā", "she", "dia"],
    ["渴望春天，", "kě wàng chūn tiān", "longs for spring", "mendambakan musim bunga"],
    ["喜欢", "xǐ huan", "loves / likes", "gemar akan / suka"],
    ["美好的", "měi hǎo de", "beautiful / wonderful", "yang indah / murni"],
    ["大自然。", "dà zì rán", "nature", "alam semula jadi."],
    ["我觉得", "wǒ jué de", "I feel", "saya berasa"],
    ["这老太太", "zhè lǎo tài tai", "this old lady", "wanita tua ini"],
    ["令人感动！’", "lìng rén gǎn dòng", "moving / touching", "membuatkan orang terharu!"],
    ["\n", "", "", ""],

    // --- 第11段 ---
    ["这时，", "zhè shí", "at this moment", "pada waktu ini"],
    ["我仔细地", "wǒ zǐ xì dì", "I carefully", "saya dengan teliti"],
    ["看了一下，", "kàn le yí xià", "looked at it for a moment", "melihat sekilas"],
    ["那位", "nà wèi", "that", "warga tua... itu"],
    ["老太太", "lǎo tài tai", "old lady", "wanita tua"],
    ["确实", "què shí", "indeed / truly", "sememangnya / benar-benar"],
    ["像我爸爸", "xiàng wǒ bà ba", "like my dad", "seperti ayah saya"],
    ["说的那样，", "shuō de nà yàng", "said like that", "katakan sedemikian"],
    ["眼睛中", "yǎn jing zhōng", "in the eyes", "di dalam mata"],
    ["闪动着", "shǎn dòng zhe", "flickering with / gleaming", "berkelip-kelip / memancarkan"],
    ["某种", "mǒu zhǒng", "some kind of", "suatu / sejenis"],
    ["渴望，", "kě wàng", "longing / yearning", "hasrat / dambaan"],
    ["荡漾在", "dàng yàng zài", "rippling on / spreading on", "terbayang-bayang di"],
    ["她脸上的", "tā liǎn shàng de", "her face's", "wajahnya punya"],
    ["笑容", "xiào róng", "smile", "senyuman"],
    ["掩饰不住", "yǎn shì bú zhù", "cannot conceal / hide", "tidak dapat menyembunyikan"],
    ["她内心的", "tā nèi xīn de", "her inner heart's", "lubuk hatinya punya"],
    ["喜悦。", "xǐ yuè", "joy / delight", "kegembiraan / sukacita."],
    ["\n", "", "", ""],

    // --- 第12段 ---
    ["爸爸", "bà ba", "dad", "ayah"],
    ["领着我", "lǐng zhe wǒ", "led me / took me", "memimpin saya"],
    ["走到", "zǒu dào", "walked to", "melangkah ke hadapan"],
    ["那位", "nà wèi", "that", "warga tua... itu"],
    ["老太太", "lǎo tài tai", "old lady", "wanita tua"],
    ["面前，", "miàn qián", "front", "hadapan"],
    ["微笑着说：", "wēi xiào zhe shuō", "said with a smile", "tersenyum sambil berkata:"],
    ["‘夫人，", "fū rén", "Madam,", "Puan,"],
    ["您欣赏", "nǐ xīn shǎng", "you appreciate", "kamu menghargai / menikmati"],
    ["春天时的", "chūn tiān shí de", "during spring's", "waktu musim bunga punya"],
    ["神情", "shén qíng", "expression / look / demeanor", "riak wajah / pandangan"],
    ["真的", "zhēn de", "really", "benar-benar"],
    ["令人感动，", "lìng rén gǎn dòng", "moving / touching", "membuatkan orang terharu"],
    ["您使", "nǐ shǐ", "you make", "kamu menyebabkan"],
    ["这春天", "zhè chūn tiān", "this spring", "musim bunga ini"],
    ["变得", "biàn de", "become", "menjadi"],
    ["更美好了！’", "gèng měi hǎo le", "even more beautiful / wonderful!", "jauh lebih indah / murni!"],
    ["\n", "", "", ""],

    // --- 第13段 ---
    ["那位", "nà wèi", "that", "warga tua... itu"],
    ["老太太", "lǎo tài tai", "old lady", "wanita tua"],
    ["似乎", "sì hū", "seemingly / as if", "nampaknya / seolah-olah"],
    ["很激动：", "hěn jī dòng", "very excited / moved", "sangat terharu / emosional:"],
    ["‘谢谢，", "xiè xie", "thank you", "terima kasih"],
    ["谢谢您！", "xiè xie nín", "thank you (respectful)", "terima kasih kepada tuan!"],
    ["先生。’", "xiān sheng", "Sir.", "Tuan."],
    ["她说着，", "tā shuō zhe", "she was saying", "sambil berkata itu"],
    ["便从", "biàn cóng", "then from", "lalu daripada"],
    ["提包里", "tí bāo lǐ", "inside the handbag", "dalam beg tangan"],
    ["取出一小袋", "qǔ chū yì xiǎo dài", "took out a small bag of", "mengeluarkan sebungkus kecil"],
    ["甜饼", "tián bǐng", "cookies / sweet biscuits", "biskut manis / kuih"],
    ["递给了我。", "dì gěi le wǒ", "handed over to me", "menghulurkan kepada saya."],
    ["‘你真", "nǐ zhēn", "you are really", "kamu sememangnya sangat"],
    ["漂亮……’", "piào liang", "beautiful / pretty", "cantik / comel..."],
    ["\n", "", "", ""],

    // --- 第14段 ---
    ["事后，", "shì hòu", "afterwards / after the event", "selepas kejadian itu / selepas itu"],
    ["爸爸", "bà ba", "dad", "ayah"],
    ["对我说：", "duì wǒ shuō", "said to me", "berkata kepada saya:"],
    ["‘一定要", "yí dìng yào", "must definitely", "semestinya perlu"],
    ["学会", "xué huì", "learn to", "belajar untuk"],
    ["真诚地", "zhēn chéng dì", "sincerely", "dengan ikhlas / tulus"],
    ["欣赏别人，", "xīn shǎng bié rén", "appreciate others", "menghargai / mengagumi orang lain"],
    ["因为", "yīn wèi", "because", "kerana"],
    ["每个人", "měi gè rén", "everyone", "setiap orang"],
    ["都有", "dōu yǒu", "all have", "mempunyai kesemuanya"],
    ["值得我们", "zhí dé wǒ men", "worthy of our", "berbaloi untuk kami"],
    ["欣赏的", "xīn shǎng de", "appreciated / admired", "hargai punya"],
    ["优点。", "yōu diǎn", "merit / advantage / strong point", "kelebihan / kebaikan."],
    ["当你", "dāng nǐ", "when you", "apabila kamu"],
    ["这样做了，", "zhè yàng zuò le", "did like this", "bertindak sedemikian"],
    ["你就会", "nǐ jiù huì", "you then will", "kamu pun akan"],
    ["获得", "huò dé", "obtain / gain / win", "mendapat / memperoleh"],
    ["很多地", "hěn duō de", "many", "banyak"],
    ["朋友。", "péng you", "friends", "sahabat / kawan."],
    ["\n", "", "", ""],

    // --- 第15段 ---
    ["听了", "tīng le", "heard", "mendengar"],
    ["希拉里的", "xī lā lǐ de", "Hillary's", "Hillary punya"],
    ["故事，", "gù shi", "story", "kisah / cerita"],
    ["谢丽", "xiè lì", "Xieli", "Xieli"],
    ["深受感动", "shēn shòu gǎn dòng", "deeply moved / touched", "amat terharu / tersentuh hati"],
    ["和", "hé", "and", "dan"],
    ["启发。", "qǐ fā", "enlightenment / inspiration", "mendapat inspirasi / kesedaran."],
    ["\n", "", "", ""],

    // --- 第16段 ---
    ["时间", "shí jiān", "time", "masa"],
    ["过得飞快，", "guò de fēi kuài", "flies by / passes quickly", "berlalu dengan amat pantas"],
    ["转眼", "zhuǎn yǎn", "in the blink of an eye", "kelip mata / sekejap sahaja"],
    ["又是", "yòu shì", "again is", "sekali lagi adalah"],
    ["一年", "yī nián", "a year", "setahun"],
    ["圣诞节", "shèng dàn jié", "Christmas", "Hari Krismas"],
    ["即将来临的", "jí jiāng lái lín de", "upcoming / around the corner", "yang bakal menjelang punya"],
    ["日子。", "rì zi", "days / time", "hari-hari / masa"],
    ["这天，", "zhè tiān", "this day", "pada hari ini"],
    ["希拉里", "xī lā lǐ", "Hillary", "Hillary"],
    ["正在家中", "zhèng zài jiā zhōng", "right at home", "sedang di dalam rumah"],
    ["忙着", "máng zhe", "busy with", "sibuk dengan"],
    ["布置", "bù zhì", "decorate / arrange", "menghias / menyusun"],
    ["圣诞树，", "shèng dàn shù", "Christmas tree", "pokok Krismas"],
    ["满脸惊喜的", "mǎn liǎn jīng xǐ de", "face full of pleasant surprise", "wajah yang penuh kejutan gembira"],
    ["谢丽", "xiè lì", "Xieli", "Xieli"],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["跑了进来，", "pǎo le jìn lái", "ran inside", "berlari masuk ke dalam"],
    ["紧紧地", "jǐn jǐn dì", "tightly", "erat-erat / dengan ketat"],
    ["抱住", "bào zhù", "embraced / hugged", "memeluk"],
    ["希拉里，", "xī lā lǐ", "Hillary", "Hillary"],
    ["说：", "shuō", "saying", "berkata:"],
    ["“谢谢你，", "xiè xie nǐ", "thank you", "terima kasih kepadamu"],
    ["今年", "jīn nián", "this year", "tahun ini"],
    ["我收到了", "wǒ shōu dào le", "I received", "saya menerima"],
    ["82张", "bā shí èr zhāng", "82 (cards)", "lapan puluh dua keping"],
    ["圣诞贺卡，", "shèng dàn hè kǎ", "Christmas cards", "kad ucapan Krismas"],
    ["比去年的", "bǐ qù nián de", "than last year's", "berbanding tahun lepas punya"],
    ["10倍", "shí bèi", "10 times", "sepuluh kali ganda"],
    ["还多！”", "hái duō", "even more!", "bahkan lebih banyak!"],
    ["\n", "", "", ""],

    // --- 第17段 ---
    ["“再算上", "zài suàn shàng", "plus / count in additionally", "kira masuk sekali / tambah lagi"],
    ["我这一张！”", "wǒ zhè yì zhāng", "this card of mine!", "saya punya sekeping ini!"],
    ["希拉里", "xī lā lǐ", "Hillary", "Hillary"],
    ["将一份", "jiāng yí fèn", "take a copy of", "menghulurkan sehelai"],
    ["印刷精美的", "yìn shuā jīng měi de", "exquisitely printed", "yang dicetak dengan indah"],
    ["贺卡", "hè kǎ", "greeting card", "kad ucapan"],
    ["递给了", "dì gěi le", "handed over to", "menyerahkan kepada"],
    ["谢丽，", "xiè lì", "Xieli", "Xieli"],
    ["上面", "shàng miàn", "on top / on it", "di atasnya"],
    ["写着", "xiě zhe", "written with", "tertulis"],
    ["这样的话：", "zhè yàng de huà", "such words", "kata-kata sedemikian:"],
    ["欣赏是", "xīn shǎng shì", "Appreciation is", "Penghargaan adalah"],
    ["架起", "jià qǐ", "build / erect", "membina / mendirikan"],
    ["友谊的", "yǒu yì de", "friendship's", "persahabatan punya"],
    ["桥梁，", "qiáo liáng", "bridge", "jambatan"],
    ["愿你我", "yuàn nǐ wǒ", "may you and I", "semoga kamu dan saya"],
    ["都能", "dōu néng", "all can", "dapat kesemuanya"],
    ["学会", "xué huì", "learn to", "belajar untuk"],
    ["真诚地", "zhēn chén dì", "sincerely", "dengan ikhlas"],
    ["欣赏别人。", "xīn shǎng bié rén", "appreciate others", "menghargai orang lain."],
    ["\n", "", "", ""],

    // --- 第18段 ---
    ["希拉里", "xī lā lǐ", "Hillary", "Hillary"],
    ["一直", "yì zhí", "always / continuously", "sentiasa / berterusan"],
    ["牢记着", "láo jì zhe", "firmly keep in mind / remember well", "sentiasa mengingati / memahat di hati"],
    ["父亲的", "bà ba de", "father's", "ayah punya"],
    ["教诲，", "jiào huì", "teachings / instructions", "ajaran / bimbingan / nasihat"],
    ["从中学", "cóng zhōng xué", "from middle school", "dari sekolah menengah"],
    ["到大学，", "dào dà xué", "to university", "ke universiti"],
    ["直到", "zhí dào", "until", "sehingga"],
    ["走向社会，", "zǒu xiàng shè huì", "enter society / career life", "melangkah masuk ke dalam masyarakat"],
    ["她的人缘", "tā de rén yuán", "her popularity / relations with people", "hubungan pergaulannya / populariti"],
    ["一直都", "yì zhí dōu", "always all", "sentiasa sememangnya"],
    ["很好，", "hěn hǎo", "very good", "amat baik"],
    ["无论", "wú lùn", "no matter / regardless of", "tidak kira / walau"],
    ["走到哪里，", "zǒu dào nǎ lǐ", "wherever she goes", "ke mana sahaja dia pergi"],
    ["她都是", "tā dōu shì", "she all is", "dia adalah kesemuanya"],
    ["大家", "dà jiā", "everyone", "orang ramai"],
    ["围绕的", "wéi rào de", "surrounding / centering around", "mengelilingi / memusatkan"],
    ["中心，", "zhōng xīn", "center / focus", "pusat / tumpuan"],
    ["直到今天，", "zhí dào jīn tiān", "until today", "sehingga hari ini"],
    ["她仍然是", "tā réng rán shì", "she still is", "dia tetap merupakan"],
    ["美国、", "měi guó", "United States", "Amerika Syarikat"],
    ["乃至", "nǎi zhì", "and even / as well as", "bahkan / sehinggakan"],
    ["全世界", "quán shì jiè", "the whole world", "seluruh dunia"],
    ["都关注的", "dōu guān zhù de", "all paying attention to / focus of", "turut memberi perhatian punya"],
    ["风云人物。", "fēng yún rén wù", "man of the hour / influential figure", "tokoh terkemuka / orang penting."],
    ["\n", "", "", ""],

    // --- 第19段 ---
    ["其实，", "qí shí", "actually / in fact", "sebenarnya / pada hakikatnya"],
    ["欣赏", "xīn shǎng", "appreciation", "penghargaan / mengagumi"],
    ["决不只是", "jué bù zhǐ shì", "is by no means only", "sama sekali bukanlah sekadar"],
    ["表面上的", "biǎo miàn shàng de", "superficial / on the surface", "luaran / pada permukaannya"],
    ["简单地", "jiǎn dān dì", "simply", "dengan mudah / ringkas"],
    ["赞美别人，", "zàn měi bié rén", "praise others / compliment others", "memuji orang lain"],
    ["更是一种", "gèng shì yì zhǒng", "even more is a kind of", "malah merupakan sejenis"],
    ["能够", "néng gòu", "able to", "mampu / boleh"],
    ["折射出", "zhé shè chū", "reflect / mirror", "mencerminkan / membayangkan"],
    ["个人", "gè rén", "one's / individual", "diri seseorang punya"],
    ["美好心灵的", "měi hǎo xīn líng de", "beautiful soul's / mind's", "jiwa / hati yang murni"],
    ["积极的", "jī jí de", "positive / active", "yang positif / aktif"],
    ["思维方式。", "sī wéi fāng shì", "way of thinking / mindset", "cara berfikir / minda."],
    ["只有", "zhǐ yǒu", "only", "hanya"],
    ["拥有春天般", "yōng yǒu chūn tiān bān", "possessing spring-like", "mempunyai seperti musim bunga"],
    ["美丽心灵的", "měi hǎo xīn líng de", "beautiful mind's", "jiwa murni punya"],
    ["人，", "rén", "people", "orang"],
    ["才会真正", "cái huì zhēn zhèng", "then will truly", "baru akan benar-benar"],
    ["领悟到", "lǐng wù dào", "comprehend / realize", "memahami / menghayati"],
    ["春天的美丽，", "chūn tiān de měi lì", "the beauty of spring", "keindahan musim bunga"],
    ["心中有阳光，", "xīn zhōng yǒu yáng guāng", "having sunshine in heart", "ada cahaya matahari di dalam hati"],
    ["眼前", "yǎn qián", "in front of eyes", "di hadapan mata"],
    ["才会亮。", "cái huì liàng", "then will be bright", "baru akan cerah."],
    ["纯洁的思想，", "chún jié de sī xiǎng", "pure thoughts", "pemikiran yang suci / bersih"],
    ["可使", "kě shǐ", "can make", "boleh menyebabkan"],
    ["微小的", "wēi xiǎo de", "tiny / minute", "perbuatan kecil"],
    ["行动", "xíng dòng", "action / deed", "tindakan / amalan"],
    ["变得", "biàn de", "become", "menjadi"],
    ["高贵。", "gāo guì", "noble / lofty", "mulia / luhur."],
    ["\n", "", "", ""],

    // --- 第20段 ---
    ["学会", "xué huì", "learn to", "belajar untuk"],
    ["欣赏别人，", "xīn shǎng bié rén", "appreciate others", "menghargai orang lain"],
    ["就会", "jiù huì", "then will", "pun akan"],
    ["养成", "yǎng chéng", "cultivate / develop (a habit)", "memupuk / membentuk"],
    ["一种", "yì zhǒng", "a kind of", "sejenis / suatu"],
    ["积极的", "jī jí de", "positive", "positif punya"],
    ["思维方式，", "sī wéi fāng shì", "way of thinking / mindset", "cara berfikir"],
    ["它可以", "tā kě yǐ", "it can", "ia boleh"],
    ["使你", "shǐ nǐ", "make you", "menyebabkan kamu"],
    ["受用一生。", "shòu yòng yī shēng", "benefit for a lifetime", "mendapat faedah sepanjang hayat."],
    ["有道是，", "yǒu dào shì", "as the saying goes,", "bak kata pepatah / ada dikatanya"],
    ["送人玫瑰，", "sòng rén méi guī", "give roses to others", "memberi bunga mawar kepada orang"],
    ["手有余香。", "shǒu yǒu yú xiāng", "hand retains lingering fragrance", "tangan masih berbau harum."],
    ["\n", "", "", ""],

    // --- 作者落款 ---
    ["（佚名《深刻的故事》）", "", "", ""]
];
